worker_processes auto;

events {
    worker_connections 1024;
}

stream {}


http {
    server {
        listen 80;
        # server_name ;

        location / {
            proxy_pass http://fotograph_strapi:1337;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-For $scheme;

        }
    }

    # server {
    #     listen 443 ssl;
    # }

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;


}