FROM node:22-slim

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Dependências necessárias para sharp e módulos nativos
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    make \
    g++ \
    autoconf \
    automake \
    zlib1g-dev \
    libpng-dev \
    bash \
    libvips-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/app

COPY package.json .
COPY yarn.lock .

RUN yarn global add node-gyp

RUN yarn install --frozen-lockfile

ENV PATH=/opt/app/node_modules/.bin:$PATH

COPY . .

USER node

EXPOSE 1337

CMD ["yarn", "develop"]